name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks a lot for the issue raised, it will be looked into as soon as possible'' first issue'
        pr-message: 'Your pull request will be looked into as soon as possible, thanks'' first pr'
